[package]
name = "orogene"
version = "0.1.0"
authors = ["Orogene Collaborative Members", "Orogene Public Contributors"]
edition = "2018"
description = "wip"
license-file = "LICENSE.md"
repository = "https://github.com/orogene/orogene"
homepage = "https://github.com/orogene/orogene"
readme = "README.md"
build = "build.rs"

[dependencies]
# Commands
cmd-ping = { path = "./commands/cmd-ping" }
cmd-view = { path = "./commands/cmd-view" }
cmd-prime = { path = "./commands/cmd-prime" }

# Workspace Deps
oro-command = { path = "./crates/oro-command" }
oro-config = { path = "./crates/oro-config" }

# Regular deps
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }
async-trait = "0.1.36"
clap = { version = "4.0.18", features = ["derive"] }
smol = "0.1.18"
directories = "3.0.1"
miette = { version = "5.4.1", features = ["fancy"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[workspace]
members = [
    ".",
    "crates/*",
    "commands/*",
]

[build-dependencies]
embed-resource = "1.3.3"

[[bin]]
name = "oro"
path = "src/main.rs"
