[package]
name = "orogene"
version = "0.1.0"
authors = ["Orogene Collaborative Members", "Orogene Public Contributors"]
edition = "2021"
description = "wip"
license-file = "LICENSE.md"
repository = "https://github.com/orogene/orogene"
homepage = "https://github.com/orogene/orogene"
readme = "README.md"
build = "build.rs"

[dependencies]
# Commands
cmd-ping = { path = "./commands/cmd-ping" }
cmd-prime = { path = "./commands/cmd-prime" }
cmd-view = { path = "./commands/cmd-view" }

# Workspace Deps
oro-command = { path = "./crates/oro-command" }
oro-config = { path = "./crates/oro-config" }

# Regular deps
async-std = { workspace = true, features = ["attributes", "unstable"] }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive"] }
directories = "3.0.1"
miette = { workspace = true, features = ["fancy"] }
tracing = { workspace = true}
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[workspace]
members = [
    ".",
    "crates/*",
    "commands/*",
]

[workspace.dependencies]
async-std = "1.12.0"
async-trait = "0.1.58"
chrono = "0.4.22"
clap = "4.0.18"
futures = "0.3.25"
maplit = "1.0.2"
miette = "5.4.1"
node-semver = "2.1.0"
nom = "7.1.1"
pretty_assertions = "1.3.0"
serde = "1.0.147"
serde_json = "1.0.87"
ssri = "7.0.0"
tempfile = "3.3.0"
thiserror = "1.0.37"
tracing = "0.1.37"
url = "2.2.2"
wiremock = "0.5.15"

[build-dependencies]
embed-resource = "1.3.3"

[[bin]]
name = "oro"
path = "src/main.rs"

[profile.release]
lto = true
