[package]
name = "node-maintainer"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2021"

[dependencies]
nassun = { path = "../nassun" }

futures = { workspace = true }
miette = { workspace = true }
node-semver = { workspace = true }
petgraph = "0.5.1"
thiserror = { workspace = true }
url = { workspace = true }
