[package]
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2021"
name = "oro-tree"
version = "0.1.0"

[dependencies]
memmap = "0.7.0"
node-semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ssri = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
