[package]
name = "rogga"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2021"

[dependencies]
oro-common = { path = "../oro-common" }
oro-client = { path = "../oro-client" }
oro-package-spec = { path = "../oro-package-spec" }

async-compression = { version = "0.3.5", features = ["gzip", "futures-io"] }
async-process = "1.0.1"
async-std = { workspace = true, features = ["attributes", "unstable"] }
async-tar = "0.2.0"
async-trait = { workspace = true }
bincode = "1.3.1"
cacache = "10.0.1"
chrono = { workspace = true, features = ["serde"] }
dashmap = "4.0.0-rc6"
futures = { workspace = true }
miette = { workspace = true }
mkdirp = "1.0.0"
node-semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ssri = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
which = "4.0.2"

[dev-dependencies]
oro-classic-resolver = { path = "../oro-classic-resolver" }
