[package]
name = "rogga"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oro-client = { path = "../oro-client" }
oro-package-spec = { path = "../oro-package-spec" }
oro-manifest = { path = "../oro-manifest" }

async-tar = "0.2.0"
async-std = { version = "1.6.2", features = ["attributes", "unstable"] }
async-compression = { version = "0.3.5", features = ["gzip", "futures-io"] }
bincode = "1.3.1"
futures = "0.3.5"
ssri = "6.0.0"
thiserror = "1.0.20"
async-trait = "0.1.36"
http-types = "2.3.0"
chrono = { version = "0.4.13", features = ["serde"] }
serde_json = "1.0.56"
serde = "1.0.114"
mkdirp = "1.0.0"
dashmap = "4.0.0-rc6"
url = "2.2.0"
tempfile = "3.1.0"
async-process = "1.0.1"
which = "4.0.2"
node-semver = "2.1.0"
miette = "5.4.1"
cacache = "10.0.1"
tracing = "0.1.37"
