[package]
name = "oro-client"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oro-common = { path = "../oro-common" }

chrono = { workspace = true }
futures = { workspace = true, features = ["io-compat"] }
miette = { workspace = true }
node-semver = { workspace = true }
# reqwest = { version = "0.11.12", features = ["json", "gzip", "stream"] }
reqwest = { git = "https://github.com/tmpfs/reqwest", branch = "wasm-bytes-stream", features = ["json", "gzip", "stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
async-std = { workspace = true, features = ["attributes", "tokio1"] }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
wiremock = { workspace = true }
