[package]
name = "oro-client"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oro-common = { path = "../oro-common" }

chrono = { workspace = true }
futures = { workspace = true, features = ["io-compat"] }
miette = { workspace = true }
node-semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
surf = { version = "2.3.2", default-features = false, features = ["encoding", "middleware-logger"]}
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
async-std = { workspace = true, features = ["attributes"] }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
wiremock = { workspace = true }

[features]
default = ["curl"]
curl = ["surf/curl-client"]
wasm = ["surf/wasm-client"]
