[package]
name = "oro-shim-bin"
version = "0.3.17"
edition = "2021"
authors = ["Kat Marchán <kzm@zkat.tech>"]
description = "Generates shims for NPM bins"
license = "ISC"
repository = "https://github.com/orogene/orogene"
homepage = "https://github.com/orogene/orogene"
readme = "README.md"
rust-version = "1.67.1"

[dependencies]
once_cell = { workspace = true }
pathdiff = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
